version: '2'

services:

  postgres:

    image: postgres:latest

    container_name: tendresse_postgres

    environment:
      POSTGRES_PASSWORD: postgres

    #expose:
    #- "5432"

    # debug mode
    ports:
    - "32768:5432"

    restart: always

    volumes:
    - $PWD/postgresql/data:/var/lib/postgresql/data

  redis:

    image: redis:latest

    container_name: tendresse_redis

    #expose:
    #- "6379"

    # debug mode
    ports:
    - "32769:6379"

    restart: always

    volumes:
      - $PWD/redis/data:/data

  tendresse:

    build: .

    container_name: tendresse_api

    depends_on:
      - redis
      - postgres

    environment:
      DEBUG: 'true'

    ports:
    - "3000:3000"

    restart: always

    volumes:
    - $PWD/redis/data:/data
